"""baseline schema

Revision ID: cf44d51dd0dd
Revises: 
Create Date: 2026-09-13 08:56:52.156639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf44d51dd0dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('default_model', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('model_filter', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoints_is_default'), 'endpoints', ['is_default'], unique=False)
    op.create_table('folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('workspace_dir', sa.String(length=512), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('propagation_mode', sa.String(length=50), nullable=False),
    sa.Column('next_req_seq', sa.Integer(), nullable=False),
    sa.Column('token_budget', sa.Integer(), nullable=False),
    sa.Column('ba_conversation_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('prompt', sa.Text(length=16777215), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('research_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=191), nullable=False),
    sa.Column('value', sa.Text(length=16777215), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('artifact_assumptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('artifact_key', sa.String(length=100), nullable=False),
    sa.Column('req_id', sa.String(length=50), nullable=False),
    sa.Column('marker_text', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_assumptions_artifact_key'), 'artifact_assumptions', ['artifact_key'], unique=False)
    op.create_index(op.f('ix_artifact_assumptions_project_id'), 'artifact_assumptions', ['project_id'], unique=False)
    op.create_table('artifact_deps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('upstream_key', sa.String(length=100), nullable=False),
    sa.Column('downstream_key', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_deps_downstream_key'), 'artifact_deps', ['downstream_key'], unique=False)
    op.create_index(op.f('ix_artifact_deps_project_id'), 'artifact_deps', ['project_id'], unique=False)
    op.create_index(op.f('ix_artifact_deps_upstream_key'), 'artifact_deps', ['upstream_key'], unique=False)
    op.create_table('artifact_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('artifact_key', sa.String(length=100), nullable=False),
    sa.Column('rel_path', sa.String(length=512), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_requests_artifact_key'), 'artifact_requests', ['artifact_key'], unique=False)
    op.create_index(op.f('ix_artifact_requests_project_id'), 'artifact_requests', ['project_id'], unique=False)
    op.create_table('artifact_traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('artifact_key', sa.String(length=100), nullable=False),
    sa.Column('req_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_traces_artifact_key'), 'artifact_traces', ['artifact_key'], unique=False)
    op.create_index(op.f('ix_artifact_traces_project_id'), 'artifact_traces', ['project_id'], unique=False)
    op.create_index(op.f('ix_artifact_traces_req_id'), 'artifact_traces', ['req_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('artifact_key', sa.String(length=100), nullable=False),
    sa.Column('role_persona_id', sa.Integer(), nullable=True),
    sa.Column('rel_path', sa.String(length=512), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('heading_index', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_persona_id'], ['personas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'artifact_key', name='uq_artifact_project_key')
    )
    op.create_index(op.f('ix_artifacts_artifact_key'), 'artifacts', ['artifact_key'], unique=False)
    op.create_index(op.f('ix_artifacts_project_id'), 'artifacts', ['project_id'], unique=False)
    op.create_table('change_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=False),
    sa.Column('from_version', sa.Integer(), nullable=False),
    sa.Column('to_version', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('changed_reqs', sa.Text(), nullable=True),
    sa.Column('removed_reqs', sa.Text(), nullable=True),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_events_project_id'), 'change_events', ['project_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('endpoint_id', sa.Integer(), nullable=True),
    sa.Column('output_dir', sa.String(length=512), nullable=False),
    sa.Column('enable_tools', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_folder_id'), 'conversations', ['folder_id'], unique=False)
    op.create_table('agent_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('raised_by_key', sa.String(length=100), nullable=False),
    sa.Column('raised_by_persona_id', sa.Integer(), nullable=True),
    sa.Column('change_id', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('req_id', sa.String(length=50), nullable=True),
    sa.Column('blocking', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('proposed_answer', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.String(length=50), nullable=True),
    sa.Column('stale_context', sa.Integer(), nullable=True),
    sa.Column('digest_message_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['change_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by_persona_id'], ['personas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_issues_project_id'), 'agent_issues', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_issues_raised_by_key'), 'agent_issues', ['raised_by_key'], unique=False)
    op.create_table('conv_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=512), nullable=False),
    sa.Column('disk_path', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('snippet', sa.Text(length=16777215), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conv_files_conversation_id'), 'conv_files', ['conversation_id'], unique=False)
    op.create_table('linked_folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('folder_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linked_folders_conversation_id'), 'linked_folders', ['conversation_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(length=16777215), nullable=False),
    sa.Column('tool_call_id', sa.String(length=255), nullable=True),
    sa.Column('tool_calls_json', sa.Text(length=16777215), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('propagation_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('artifact_key', sa.String(length=100), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['change_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propagation_jobs_artifact_key'), 'propagation_jobs', ['artifact_key'], unique=False)
    op.create_index(op.f('ix_propagation_jobs_change_id'), 'propagation_jobs', ['change_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_propagation_jobs_change_id'), table_name='propagation_jobs')
    op.drop_index(op.f('ix_propagation_jobs_artifact_key'), table_name='propagation_jobs')
    op.drop_table('propagation_jobs')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_linked_folders_conversation_id'), table_name='linked_folders')
    op.drop_table('linked_folders')
    op.drop_index(op.f('ix_conv_files_conversation_id'), table_name='conv_files')
    op.drop_table('conv_files')
    op.drop_index(op.f('ix_agent_issues_raised_by_key'), table_name='agent_issues')
    op.drop_index(op.f('ix_agent_issues_project_id'), table_name='agent_issues')
    op.drop_table('agent_issues')
    op.drop_index(op.f('ix_conversations_folder_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_change_events_project_id'), table_name='change_events')
    op.drop_table('change_events')
    op.drop_index(op.f('ix_artifacts_project_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_artifact_key'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_artifact_traces_req_id'), table_name='artifact_traces')
    op.drop_index(op.f('ix_artifact_traces_project_id'), table_name='artifact_traces')
    op.drop_index(op.f('ix_artifact_traces_artifact_key'), table_name='artifact_traces')
    op.drop_table('artifact_traces')
    op.drop_index(op.f('ix_artifact_requests_project_id'), table_name='artifact_requests')
    op.drop_index(op.f('ix_artifact_requests_artifact_key'), table_name='artifact_requests')
    op.drop_table('artifact_requests')
    op.drop_index(op.f('ix_artifact_deps_upstream_key'), table_name='artifact_deps')
    op.drop_index(op.f('ix_artifact_deps_project_id'), table_name='artifact_deps')
    op.drop_index(op.f('ix_artifact_deps_downstream_key'), table_name='artifact_deps')
    op.drop_table('artifact_deps')
    op.drop_index(op.f('ix_artifact_assumptions_project_id'), table_name='artifact_assumptions')
    op.drop_index(op.f('ix_artifact_assumptions_artifact_key'), table_name='artifact_assumptions')
    op.drop_table('artifact_assumptions')
    op.drop_table('settings')
    op.drop_table('research_sources')
    op.drop_table('personas')
    op.drop_table('folders')
    op.drop_index(op.f('ix_endpoints_is_default'), table_name='endpoints')
    op.drop_table('endpoints')
    # ### end Alembic commands ###
